name: Dispatchable Version Bump

on:
  workflow_dispatch:
    inputs:
      version_increment:
        description: "Version increment type (patch, minor, major, or custom)"
        required: true
        default: "patch"
      custom_version:
        description: "Custom version (only if version_increment is custom)"
        required: false

jobs:
  bump-version:
    runs-on: ubuntu-latest

    steps:
      - name: Use PackBumpPR
        uses: HichemTab-tech/PackBumpPR@v1
        with:
          version_increment: ${{ github.event.inputs.version_increment }}
          custom_version: ${{ github.event.inputs.custom_version }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          main_branche: "main" # or "master"